# Generated by Django 6.0.5 on 2026-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('response_time', models.IntegerField(blank=True, null=True)),
                ('http_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('interval_minutes', models.IntegerField(default=5)),
                ('is_paused', models.BooleanField(default=False)),
                ('last_status', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('unknown', 'unknown')], default='unknown', max_length=20)),
                ('last_http_code', models.IntegerField(blank=True, null=True)),
                ('last_response_time', models.IntegerField(blank=True, null=True)),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
                ('uptime_pct', models.FloatField(default=100.0)),
                ('email1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('email3', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
